# Generated by Django 2.2.12 on 2020-05-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providergame_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='providergame',
            unique_together={('slug', 'provider')},
        ),
    ]
