# Generated by Django 2.2.12 on 2021-12-21 07:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20200523_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platforms', to='providers.Provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='providers.Provider')),
            ],
        ),
    ]
