# Generated by Django 2.2.12 on 2021-12-21 23:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_providergenre_providerplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.IntegerField()),
                ('image_id', models.SlugField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covers', to='providers.Provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
