# Generated by Django 2.2.12 on 2021-12-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_providercover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercover',
            name='game',
            field=models.IntegerField(null=True),
        ),
    ]
