# Generated by Django 2.2.12 on 2022-02-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_auto_20211222_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='providergame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
