# Generated by Django 2.2.12 on 2022-05-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_auto_20220217_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercover',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='providergame',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='providergenre',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='providerplatform',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
