# Generated by Django 4.2.1 on 2024-04-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("providers", "0012_alter_provider_id_alter_providercover_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providergame",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
