# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0006_auto_20151111_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runnerversion',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runner_versions', to='runners.Runner'),
        ),
    ]
