# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0007_auto_20160820_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='architecture',
            field=models.CharField(choices=[(b'i386', b'32 bit'), (b'x86_64', b'64 bit'), (b'armv7', b'ARM'), (b'all', b'All')], default=b'all', max_length=8),
        ),
        migrations.AlterField(
            model_name='runnerversion',
            name='architecture',
            field=models.CharField(choices=[(b'i386', b'32 bit'), (b'x86_64', b'64 bit'), (b'armv7', b'ARM'), (b'all', b'All')], default=b'x86_64', max_length=8),
        ),
    ]
