# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0008_auto_20161024_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='icon',
            field=models.ImageField(blank=True, upload_to='runners/icons'),
        ),
        migrations.AlterField(
            model_name='runnerversion',
            name='architecture',
            field=models.CharField(choices=[('i386', '32 bit'), ('x86_64', '64 bit'), ('armv7', 'ARM'), ('all', 'All')], default='x86_64', max_length=8),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='architecture',
            field=models.CharField(choices=[('i386', '32 bit'), ('x86_64', '64 bit'), ('armv7', 'ARM'), ('all', 'All')], default='all', max_length=8),
        ),
    ]
