# Generated by Django 4.2.1 on 2023-06-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0013_alter_runner_id_alter_runnerversion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='versioned',
            field=models.BooleanField(default=False),
        ),
    ]
