# Generated by Django 4.2.1 on 2023-08-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runners', '0016_alter_runtime_min_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
