# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20170418_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content_markup_type',
            field=models.CharField(choices=[(b'', b'--'), (b'html', 'HTML'), (b'plain', 'Plain'), (b'restructuredtext', 'Restructured Text')], default=b'restructuredtext', editable=False, max_length=30),
        ),
    ]
