# Generated by Django 2.2.12 on 2020-04-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_upload_hosting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='destination',
            field=models.CharField(max_length=256, verbose_name='destination path'),
        ),
    ]
