# Generated by Django 2.2.12 on 2022-10-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_keyvaluestore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvaluestore',
            name='key',
            field=models.CharField(max_length=64),
        ),
    ]
