# Generated by Django 4.2.1 on 2023-08-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_keyvaluestore_id_alter_news_id_alter_upload_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='_content_rendered',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_markup_type',
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
