# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='section',
            field=models.CharField(default='TOSEC', max_length=12),
        ),
    ]
