# Generated by Django 2.2.12 on 2023-01-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tosec', '0002_auto_20180515_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TosecCategory',
        ),
        migrations.RenameModel(
            old_name='Game',
            new_name='TosecGame',
        ),
        migrations.RenameModel(
            old_name='Rom',
            new_name='TosecRom',
        ),
    ]
