# Generated by Django 2.2.12 on 2023-01-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosec', '0003_auto_20230118_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toseccategory',
            name='author',
            field=models.TextField(),
        ),
    ]
