# Generated by Django 2.2.12 on 2023-01-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosec', '0004_auto_20230118_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tosecrom',
            name='size',
            field=models.BigIntegerField(),
        ),
    ]
