# Generated by Django 4.2.1 on 2025-06-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_emailconfirmationtoken_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_adult_content",
            field=models.BooleanField(default=False),
        ),
    ]
