# Generated by Django 5.2.11 on 2026-03-14 18:59

from django.db import migrations


def migrate_steam_accounts(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    SocialAccount = apps.get_model("socialaccount", "SocialAccount")

    users_with_steam = User.objects.exclude(steamid="").exclude(steamid__isnull=True)
    created = 0
    skipped = 0
    for user in users_with_steam.iterator():
        # The unique constraint is on (provider, uid), so if another user
        # already claimed this steamid, skip it.
        if SocialAccount.objects.filter(provider="steam", uid=user.steamid).exists():
            skipped += 1
            continue
        SocialAccount.objects.create(
            user=user,
            provider="steam",
            uid=user.steamid,
            extra_data={},
        )
        created += 1
    print(f"\nMigrated {created} Steam accounts to allauth SocialAccount "
          f"({skipped} skipped due to duplicate steamid)")


def reverse_migration(apps, schema_editor):
    SocialAccount = apps.get_model("socialaccount", "SocialAccount")
    SocialAccount.objects.filter(provider="steam").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_user_show_adult_content"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.RunPython(migrate_steam_accounts, reverse_migration),
    ]
