# Generated by Django 5.2.11 on 2026-05-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_migrate_steam_to_allauth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_setup_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
