# Generated by Django 4.2.1 on 2023-07-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_squashed_0007_feature_featureset_alter_feature_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='featureset',
            new_name='feature_level',
        ),
        migrations.AddField(
            model_name='generation',
            name='introduced_with',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
