# Generated by Django 4.2.1 on 2023-07-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_rename_featureset_feature_feature_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.generation'),
        ),
    ]
