DEMO_FLAGS = {
    'demo': "General demonstration version",
    'demo-kiosk': "Retail demo units and kiosks",
    'demo-playable': "General demonstration version, playable",
    'demo-rolling': "General demonstration version, non-interactive",
    'demo-slideshow': "General demonstration version, non-interactive slideshow",
}

SYSTEMS_FLAGS = {
    '+ 2': "Sinclair ZX Spectrum",
    '+ 2a': "Sinclair ZX Spectrum",
    '+ 3': "Sinclair ZX Spectrum",
    '130XE': "Atari 8-bit",
    'A1000': "Commodore Amiga",
    'A1200': "Commodore Amiga",
    'A1200-A4000': "Commodore Amiga",
    'A2000': "Commodore Amiga",
    'A2000-A3000': "Commodore Amiga",
    'A2024': "Commodore Amiga",
    'A2500-A3000UX': "Commodore Amiga",
    'A3000': "Commodore Amiga",
    'A4000': "Commodore Amiga",
    'A4000T': "Commodore Amiga",
    'A500': "Commodore Amiga",
    'A500': "Commodore Amiga",
    'A500-A1000-A2000': "Commodore Amiga",
    'A500-A1000-A2000-CDTV': "Commodore Amiga",
    'A500-A1200': "Commodore Amiga",
    'A500-A1200-A2000-A4000': "Commodore Amiga",
    'A500-A2000': "Commodore Amiga",
    'A500-A600-A2000': "Commodore Amiga",
    'A570': "Commodore Amiga",
    'A600': "Commodore Amiga",
    'A600HD': "Commodore Amiga",
    'AGA': "Commodore Amiga",
    'AGA-CD32': "Commodore Amiga",
    'Aladdin': "Deck Enhancer Nintendo NES",
    'CD32': "Commodore Amiga",
    'CDTV': "Commodore Amiga",
    'Computrainer': "Nintendo NES",
    'Doctor PC Jr.': "Nintendo NES",
    'ECS': "Commodore Amiga",
    'ECS-AGA': "Commodore Amiga",
    'Executive': "Osborne OSBORNE 1 & Executive",
    'Mega ST': "Atari ST",
    'Mega-STE': "Atari ST",
    'OCS': "Commodore Amiga",
    'OCS-AGA': "Commodore Amiga",
    'ORCH80': "???",
    'Osbourne': "1 Osborne OSBORNE 1 & Executive",
    'PIANO90': "???",
    'PlayChoice-10': "Nintendo NES",
    'Plus4': "???",
    'Primo-A': "Microkey Primo",
    'Primo-A64': "Microkey Primo",
    'Primo-B': "Microkey Primo",
    'Primo-B64': "Microkey Primo",
    'Pro-Primo': "Microkey Primo",
    'ST': "Atari ST",
    'STE': "Atari ST",
    'STE-Falcon': "???",
    'TT': "Atari ST",
    'TURBO-R': "GT MSX",
    'TURBO-R': "ST MSX",
    'VS DualSystem': "Nintendo NES",
    'VS UniSystem': "Nintendo NES",
}


VIDEO_FLAGS = {
    'CGA': "?",
    'EGA': "?",
    'HGC': "?",
    'MCGA': "?",
    'MDA': "?",
    'NTSC': "?",
    'NTSC-PAL': "?",
    'PAL': "?",
    'PAL-60': "?",
    'PAL-NTSC': "?",
    'SVGA': "?",
    'VGA': "?",
    'XGA': "?",
}
