DEMO_FLAGS = {
    'demo': "General demonstration version",
    'demo-kiosk': "Retail demo units and kiosks",
    'demo-playable': "General demonstration version, playable",
    'demo-rolling': "General demonstration version, non-interactive",
    'demo-slideshow': "General demonstration version, non-interactive slideshow",
}

SYSTEMS_FLAGS = {
    '+ 2': "Sinclair ZX Spectrum",
    '+ 2a': "Sinclair ZX Spectrum",
    '+ 3': "Sinclair ZX Spectrum",
    '130XE': "Atari 8-bit",
    'A1000': "Commodore Amiga",
    'A1200': "Commodore Amiga",
    'A1200-A4000': "Commodore Amiga",
    'A2000': "Commodore Amiga",
    'A2000-A3000': "Commodore Amiga",
    'A2024': "Commodore Amiga",
    'A2500-A3000UX': "Commodore Amiga",
    'A3000': "Commodore Amiga",
    'A4000': "Commodore Amiga",
    'A4000T': "Commodore Amiga",
    'A500': "Commodore Amiga",
    'A500-A1000-A2000': "Commodore Amiga",
    'A500-A1000-A2000-CDTV': "Commodore Amiga",
    'A500-A1200': "Commodore Amiga",
    'A500-A1200-A2000-A4000': "Commodore Amiga",
    'A500-A2000': "Commodore Amiga",
    'A500-A600-A2000': "Commodore Amiga",
    'A570': "Commodore Amiga",
    'A600': "Commodore Amiga",
    'A600HD': "Commodore Amiga",
    'AGA': "Commodore Amiga",
    'AGA-CD32': "Commodore Amiga",
    'Aladdin': "Deck Enhancer Nintendo NES",
    'CD32': "Commodore Amiga",
    'CDTV': "Commodore Amiga",
    'Computrainer': "Nintendo NES",
    'Doctor PC Jr.': "Nintendo NES",
    'ECS': "Commodore Amiga",
    'ECS-AGA': "Commodore Amiga",
    'Executive': "Osborne OSBORNE 1 & Executive",
    'Mega ST': "Atari ST",
    'Mega-STE': "Atari ST",
    'OCS': "Commodore Amiga",
    'OCS-AGA': "Commodore Amiga",
    'ORCH80': "???",
    'Osbourne': "1 Osborne OSBORNE 1 & Executive",
    'PIANO90': "???",
    'PlayChoice-10': "Nintendo NES",
    'Plus4': "???",
    'Primo-A': "Microkey Primo",
    'Primo-A64': "Microkey Primo",
    'Primo-B': "Microkey Primo",
    'Primo-B64': "Microkey Primo",
    'Pro-Primo': "Microkey Primo",
    'ST': "Atari ST",
    'STE': "Atari ST",
    'STE-Falcon': "???",
    'TT': "Atari ST",
    'TURBO-R': "GT MSX",
    'VS DualSystem': "Nintendo NES",
    'VS UniSystem': "Nintendo NES",
}


VIDEO_FLAGS = {
    'CGA': "?",
    'EGA': "?",
    'HGC': "?",
    'MCGA': "?",
    'MDA': "?",
    'NTSC': "?",
    'NTSC-PAL': "?",
    'PAL': "?",
    'PAL-60': "?",
    'PAL-NTSC': "?",
    'SVGA': "?",
    'VGA': "?",
    'XGA': "?",
}

COUNTRY_FLAGS = {
    'AE': 'United Arab Emirates',
    'AL': 'Albania',
    'AS': 'Asia',
    'AT': 'Austria',
    'AU': 'Australia',
    'BA': 'Bosnia and Herzegovina',
    'BE': 'Belgium',
    'BG': 'Bulgaria',
    'BR': 'Brazil',
    'CA': 'Canada',
    'CH': 'Switzerland',
    'CL': 'Chile',
    'CN': 'China',
    'CS': 'Serbia and Montenegro',
    'CY': 'Cyprus',
    'CZ': 'Czech Republic',
    'DE': 'Germany',
    'DK': 'Denmark',
    'EE': 'Estonia',
    'EG': 'Egypt',
    'ES': 'Spain',
    'EU': 'Europe',
    'FI': 'Finland',
    'FR': 'France',
    'GB': 'United Kingdom',
    'GR': 'Greece',
    'HK': 'Hong Kong',
    'HR': 'Croatia',
    'HU': 'Hungary',
    'ID': 'Indonesia',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IN': 'India',
    'IR': 'Iran',
    'IS': 'Iceland',
    'IT': 'Italy',
    'JO': 'Jordan',
    'JP': 'Japan',
    'KR': 'South Korea',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'LV': 'Latvia',
    'MN': 'Mongolia',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'NP': 'Nepal',
    'NZ': 'New Zealand',
    'OM': 'Oman',
    'PE': 'Peru',
    'PH': 'Philippines',
    'PL': 'Poland',
    'PT': 'Portugal',
    'QA': 'Qatar',
    'RO': 'Romania',
    'RU': 'Russia',
    'SE': 'Sweden',
    'SG': 'Singapore',
    'SI': 'Slovenia',
    'SK': 'Slovakia',
    'TH': 'Thailand',
    'TR': 'Turkey',
    'TW': 'Taiwan',
    'US': 'United States',
    'VN': 'Vietnam',
    'YU': 'Yugoslavia',
    'ZA': 'South Africa',
}

LANGUAGE_FLAGS = {
    'ar': 'Arabic',
    'bg': 'Bulgarian',
    'bs': 'Bosnian',
    'cs': 'Czech',
    'cy': 'Welsh',
    'da': 'Danish',
    'de': 'German',
    'el': 'Greek',
    'en': 'English',
    'eo': 'Esperanto',
    'es': 'Spanish',
    'et': 'Estonian',
    'fa': 'Persian',
    'fi': 'Finnish',
    'fr': 'French',
    'ga': 'Irish',
    'gu': 'Gujarati',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'hr': 'Croatian',
    'hu': 'Hungarian',
    'is': 'Icelandic',
    'it': 'Italian',
    'ja': 'Japanese',
    'ko': 'Korean',
    'lt': 'Lithuanian',
    'lv': 'Latvian',
    'ms': 'Malay',
    'nl': 'Dutch',
    'no': 'Norwegian',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ro': 'Romanian',
    'ru': 'Russian',
    'sk': 'Slovakian',
    'sl': 'Slovenian',
    'sq': 'Albanian',
    'sr': 'Serbian',
    'sv': 'Swedish',
    'th': 'Thai',
    'tr': 'Turkish',
    'ur': 'Urdu',
    'vi': 'Vietnamese',
    'yi': 'Yiddish',
    'zh': 'Chinese',
}

COPYRIGHT_FLAGS = {
    'CW': 'Cardware',
    'CW-': 'ardware-Registered',
    'FW': 'Freeware',
    'GW': 'Giftware',
    'GW-': 'iftware-Registered',
    'LW': 'Licenceware',
    'PD': 'Public Domain',
    'SW': 'Shareware',
    'SW-': 'hareware-Registered',
}

DEVELOPMENT_FLAGS = {
    'alpha': 'Early test build',
    'beta': 'Later, feature complete test build',
    'preview': 'Near complete build',
    'pre-release': 'Near complete build',
    'proto': 'Unreleased, prototype software',
}

MEDIA_FLAGS = {
    'Disc': 'Optical disc based media',
    'Disk': 'Magnetic disk based media',
    'File': 'Individual files',
    'Part': 'Individual parts',
    'Side': 'Side of media',
    'Tape': 'Magnetic tape based media',
}

DUMP_INFO_FLAGS = {
    'cr': 'Cracked',
    'f': 'Fixed',
    'h': 'Hacked',
    'm': 'Modified',
    'p': 'Pirated',
    't': 'Trained',
    'tr': 'Translated',
    'o': 'Over Dump',
    'u': 'Under Dump',
    'v': 'Virus',
    'b': 'Bad Dump',
    'a': 'Alternate',
    '!': 'Verified',
}
