# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20160509_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installer',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
