# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20160612_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='rating',
            field=models.CharField(blank=True, choices=[(b'platinum', b'Platinum: installs and runs flawlessly'), (b'gold', b'Gold: works flawlessly with some minor tweaking'), (b'silver', b'Silver: works excellently for "normal" use but some features may be broken'), (b'bronze', b'Bronze: works, but has some issues, even for normal use'), (b'garbage', b'Garbage: game is not playable')], max_length=24),
        ),
    ]
