# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_installer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installer',
            name='rating',
            field=models.CharField(blank=True, choices=[(b'platinum', b'Platinum: installs and runs flawlessly'), (b'garbage', b'Garbage: game is not playable'), (b'bronze', b'Bronze: works: but has some issues: even for normal use'), (b'silver', b'Silver: works excellently for "normal" use but some features may be broken'), (b'gold', b'Gold: works flawlessly with some minor tweaking')], max_length=24),
        ),
    ]
