# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20160615_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, choices=[(b'wikipedia', b'Wikipedia'), (b'pcgamingwiki', b'PCGamingWiki'), (b'mobygames', b'MobyGames'), (b'winehq', b'WineHQ AppDB'), (b'lemonamiga', b'Lemon Amiga')], max_length=32)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name'], 'permissions': (('can_publish_game', 'Can publish game'),)},
        ),
        migrations.AlterField(
            model_name='installer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installers', to='games.Game'),
        ),
        migrations.AddField(
            model_name='gamelink',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
