# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20161001_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelink',
            name='accepted_at',
        ),
    ]
