# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20161001_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamelink',
            options={'ordering': ['website'], 'verbose_name': 'External link'},
        ),
        migrations.AlterField(
            model_name='gamelink',
            name='website',
            field=models.CharField(blank=True, choices=[(b'wikipedia', b'Wikipedia'), (b'pcgamingwiki', b'PCGamingWiki'), (b'mobygames', b'MobyGames'), (b'winehq', b'WineHQ AppDB'), (b'lemonamiga', b'Lemon Amiga'), (b'github', b'Github')], max_length=32),
        ),
    ]
