# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 11:56
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def create_revisions(apps, schema_editor):
    call_command('createinitialrevisions')


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_installer_draft'),
    ]

    operations = [
        migrations.RunPython(create_revisions)
    ]
