# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_autoinstaller_installerrevision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gogid',
            new_name='gogslug',
        ),
    ]
