# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-14 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20170608_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gogid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
