# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-14 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_game_gogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gogid',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
