# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-24 03:48
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_auto_20170614_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='flags',
            field=bitfield.models.BitField(((b'fully_libre', b'Fully libre'), (b'open_engine', b'Open engine only'), (b'free', b'Free'), (b'freetoplay', b'Free-to-play'), (b'pwyw', b'Pay what you want'), (b'demo', b'Has a demo'), (b'protected', b'Installer modification is restricted')), default=None),
        ),
    ]
