# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20170824_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='change_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
