# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-04 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20170824_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='reason',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
