# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 19:30
from __future__ import unicode_literals

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_auto_20171104_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='companies/logos'),
        ),
        migrations.AlterField(
            model_name='featured',
            name='image',
            field=models.ImageField(upload_to='featured'),
        ),
        migrations.AlterField(
            model_name='game',
            name='flags',
            field=bitfield.models.BitField((('fully_libre', 'Fully libre'), ('open_engine', 'Open engine only'), ('free', 'Free'), ('freetoplay', 'Free-to-play'), ('pwyw', 'Pay what you want'), ('demo', 'Has a demo'), ('protected', 'Installer modification is restricted')), default=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, upload_to='games/icons'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title_logo',
            field=models.ImageField(blank=True, upload_to='games/banners'),
        ),
        migrations.AlterField(
            model_name='gamelink',
            name='website',
            field=models.CharField(blank=True, choices=[('wikipedia', 'Wikipedia'), ('pcgamingwiki', 'PCGamingWiki'), ('mobygames', 'MobyGames'), ('winehq', 'WineHQ AppDB'), ('lemonamiga', 'Lemon Amiga'), ('github', 'Github')], max_length=32),
        ),
        migrations.AlterField(
            model_name='installer',
            name='rating',
            field=models.CharField(blank=True, choices=[('platinum', 'Platinum: installs and runs flawlessly'), ('gold', 'Gold: works flawlessly with some minor tweaking'), ('silver', 'Silver: works excellently for "normal" use but some features may be broken'), ('bronze', 'Bronze: works: but has some issues: even for normal use'), ('garbage', 'Garbage: game is not playable')], max_length=24),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(upload_to='games/screenshots'),
        ),
    ]
