# Generated by Django 2.0.5 on 2018-11-18 17:19

from django.db import migrations


def convert_ratings(apps, schema_editor):
    """Convert rating names to sortable values"""
    Installer = apps.get_model('games', 'Installer')  # pylint: disable=invalid-name
    Installer.objects.filter(rating='garbage').update(rating='1')
    Installer.objects.filter(rating='bronze').update(rating='2')
    Installer.objects.filter(rating='silver').update(rating='3')
    Installer.objects.filter(rating='gold').update(rating='4')
    Installer.objects.filter(rating='platinum').update(rating='5')


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_auto_20181108_0959'),
    ]

    operations = [
        migrations.RunPython(convert_ratings),
    ]
