# Generated by Django 2.0.5 on 2018-11-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_auto_20181118_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installer',
            options={'ordering': ('-rating', 'version')},
        ),
        migrations.AddField(
            model_name='installer',
            name='protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='installer',
            name='rating',
            field=models.CharField(blank=True, choices=[('5', 'Platinum: installs and runs flawlessly'), ('4', 'Gold: works flawlessly with some minor tweaking'), ('3', 'Silver: works excellently for "normal" use but some features may be broken'), ('2', 'Bronze: works: but has some issues: even for normal use'), ('1', 'Garbage: game is not playable')], max_length=24),
        ),
        migrations.AlterField(
            model_name='installerissue',
            name='installer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='games.Installer'),
        ),
    ]
