# Generated by Django 2.0.5 on 2018-11-25 06:09

from django.db import migrations


def convert_protected(apps, schema_editor):
    """Installer now have a protected field"""
    Game = apps.get_model('games', 'Game')
    for game in Game.objects.filter(flags=Game.flags.protected):
        for installer in game.installers.all():
            installer.protected = True
            installer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_auto_20181125_0609'),
    ]

    operations = [
        migrations.RunPython(convert_protected),
    ]
