# Generated by Django 2.0.5 on 2018-12-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_auto_20181207_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installerhistory',
            name='slug',
        ),
    ]
