# Generated by Django 2.0.5 on 2018-12-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_remove_installerhistory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
