# Generated by Django 2.0.5 on 2019-02-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_gamealias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamealias',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='games.Game'),
        ),
    ]
