# Generated by Django 2.0.5 on 2020-01-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0039_auto_20190205_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelink',
            name='website',
            field=models.CharField(blank=True, choices=[('battlenet', 'Battle.net'), ('github', 'Github'), ('isthereanydeal', 'IsThereAnyDeal'), ('lemonamiga', 'Lemon Amiga'), ('mobygames', 'MobyGames'), ('origin', 'Origin'), ('pcgamingwiki', 'PCGamingWiki'), ('ubisoft', 'Ubisoft'), ('wikipedia', 'Wikipedia'), ('winehq', 'WineHQ AppDB')], max_length=32),
        ),
    ]
