# Generated by Django 2.2.12 on 2020-04-29 18:05

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_auto_20200116_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='title_logo',
            new_name='banner'
        ),
        migrations.AlterField(
            model_name='game',
            name='banner',
            field=models.ImageField(blank=True, upload_to=games.models.game_banner_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to=games.models.company_logo_path),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, upload_to=games.models.game_icon_path),
        ),
    ]
