# Generated by Django 2.2.12 on 2020-05-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_providergame_metadata'),
        ('games', '0040_auto_20200116_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='provider_games',
            field=models.ManyToManyField(related_name='games', to='providers.ProviderGame'),
        ),
    ]
