# Generated by Django 2.2.12 on 2020-05-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_game_provider_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, to='games.Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/icons'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='platforms.Platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='provider_games',
            field=models.ManyToManyField(blank=True, related_name='games', to='providers.ProviderGame'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title_logo',
            field=models.ImageField(blank=True, upload_to='uploads/banners'),
        ),
    ]
