# Generated by Django 2.2.12 on 2021-04-18 04:18

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_auto_20200529_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='flags',
            field=bitfield.models.BitField((('fully_libre', 'Fully libre'), ('open_engine', 'Open engine only'), ('free', 'Free'), ('freetoplay', 'Free-to-play'), ('pwyw', 'Pay what you want'), ('protected', 'Installer modification is restricted')), default=None),
        ),
    ]
