# Generated by Django 2.2.12 on 2021-05-18 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_auto_20200529_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesubmission',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='games.Game'),
        ),
        migrations.AlterField(
            model_name='gamesubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
