# Generated by Django 2.2.12 on 2021-08-24 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0043_auto_20210518_0004'),
        ('games', '0043_auto_20210418_0418'),
    ]

    operations = [
    ]
