# Generated by Django 2.2.12 on 2021-10-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0043_auto_20210518_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
