# Generated by Django 2.2.12 on 2021-12-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0044_merge_20210824_0154'),
        ('games', '0044_auto_20211023_1825'),
    ]

    operations = [
    ]
