# Generated by Django 2.2.12 on 2021-12-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0045_merge_20211208_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installer',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
