# Generated by Django 2.2.12 on 2021-12-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0046_auto_20211216_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
