# Generated by Django 2.2.12 on 2021-12-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0048_auto_20211223_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='coverart',
            field=models.ImageField(blank=True, upload_to='uploads/coverart'),
        ),
    ]
