# Generated by Django 2.2.12 on 2022-01-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0051_auto_20220106_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='review',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
