# Generated by Django 2.2.12 on 2022-03-22 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0052_installer_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installer',
            options={'ordering': ('version',)},
        ),
        migrations.AddField(
            model_name='installer',
            name='credits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='installer',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='installer',
            name='rating',
            field=models.CharField(blank=True, choices=[('5', 'Platinum (this rating is meaningless)'), ('4', 'Gold (this rating is meaningless)'), ('3', 'Silver (this rating is meaningless)'), ('2', 'Bronze (this rating is meaningless)'), ('1', 'Garbage (this rating is meaningless)')], max_length=24),
        ),
    ]
