# Generated by Django 2.2.12 on 2022-06-08 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0053_auto_20220322_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playable', models.BooleanField()),
                ('verified', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('installer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='games.Installer')),
            ],
        ),
        migrations.CreateModel(
            name='Quirk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quirks', to='games.Rating')),
            ],
        ),
    ]
