# Generated by Django 2.2.12 on 2022-09-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0054_quirk_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discord_id',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
    ]
