# Generated by Django 2.2.12 on 2022-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0055_game_discord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discord_id',
            field=models.CharField(blank=True, default='', max_length=18, null=True),
        ),
    ]
