# Generated by Django 2.2.12 on 2022-10-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0056_auto_20220904_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShaderCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=256)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shaders', to='games.Game')),
            ],
        ),
    ]
