# Generated by Django 2.2.12 on 2023-01-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0057_shadercache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameMetadata',
        ),
    ]
