# Generated by Django 2.2.12 on 2023-01-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0060_auto_20230114_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='installerdraft',
            name='credits',
            field=models.TextField(blank=True),
        ),
    ]
