# Generated by Django 2.2.12 on 2023-01-14 05:55

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0062_auto_20230114_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installer',
            name='protected',
        ),
        migrations.AlterField(
            model_name='game',
            name='flags',
            field=bitfield.models.BitField((('fully_libre', 'Fully libre'), ('open_engine', 'Open engine only'), ('free', 'Free'), ('freetoplay', 'Free-to-play'), ('pwyw', 'Pay what you want')), default=None),
        ),
    ]
