# Generated by Django 2.2.12 on 2023-01-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0064_auto_20230116_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstallerRevision',
        ),
    ]
