# Generated by Django 4.2.1 on 2023-07-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0067_alter_installer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='pin_reason',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='installer',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
