# Generated by Django 4.2.1 on 2023-12-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0068_installer_pin_reason_installer_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='installer',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
