# Generated by Django 4.2.1 on 2024-02-09 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0070_alter_game_flags"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE games_gamelibrary_games RENAME TO games_librarygame",
                    reverse_sql="ALTER TABLE games_librarygame RENAME TO games_gamelibrary_games",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="LibraryGame",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "game",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to="games.game"
                            ),
                        ),
                        (
                            "gamelibrary",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="games.gamelibrary",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="gamelibrary",
                    name="games",
                    field=models.ManyToManyField(
                        to="games.Game",
                        through="games.LibraryGame",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="LibraryGame",
            name="playtime",
            field=models.FloatField(default=0),
        ),
    ]
