# Generated by Django 4.2.1 on 2024-02-09 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0071_librarygame_alter_gamelibrary_games"),
    ]

    operations = [
        migrations.CreateModel(
            name="NonLutrisGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("slug", models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name="gamelibrary",
            name="games",
            field=models.ManyToManyField(
                related_name="libraries", through="games.LibraryGame", to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="librarygame",
            name="game",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="games.game"
            ),
        ),
        migrations.AlterField(
            model_name="librarygame",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="StoreLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="librarygame",
            name="non_lutris_game",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="games.nonlutrisgame",
            ),
        ),
    ]
