# Generated by Django 4.2.1 on 2024-02-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0072_nonlutrisgame_alter_gamelibrary_games_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarygame",
            name="lastplayed",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="librarygame",
            name="platform",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="librarygame",
            name="runner",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="librarygame",
            name="service",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="librarygame",
            name="service_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="librarygame",
            name="playtime",
            field=models.FloatField(default=0, null=True),
        ),
    ]
