# Generated by Django 4.2.1 on 2024-02-13 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0073_librarygame_lastplayed_librarygame_platform_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="librarygame",
            name="non_lutris_game",
        ),
        migrations.DeleteModel(
            name="NonLutrisGame",
        ),
    ]
