# Generated by Django 4.2.1 on 2024-02-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0074_remove_librarygame_non_lutris_game_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarygame",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="librarygame",
            name="slug",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
