# Generated by Django 4.2.1 on 2024-02-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0075_librarygame_name_librarygame_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamelibrary",
            name="games",
        ),
        migrations.AlterField(
            model_name="librarygame",
            name="gamelibrary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="games.gamelibrary",
            ),
        ),
    ]
