# Generated by Django 4.2.1 on 2024-02-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0077_alter_librarygame_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarygame",
            name="lastplayed",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
