# Generated by Django 4.2.1 on 2024-02-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0078_alter_librarygame_lastplayed"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarygame",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
