# Generated by Django 4.2.1 on 2024-02-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0080_librarycategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarygame",
            name="categories",
            field=models.ManyToManyField(blank=True, to="games.librarycategory"),
        ),
    ]
