# Generated by Django 4.2.1 on 2025-06-02 13:35

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0081_librarygame_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="flags",
            field=bitfield.models.BitField(
                (
                    ("fully_libre", "Fully libre"),
                    ("open_engine", "Open engine only"),
                    ("free", "Free"),
                    ("freetoplay", "Free-to-play"),
                    ("pwyw", "Pay what you want"),
                    ("kernel_ac", "Infected with kernel level anticheat"),
                    ("adult_only", "Adult only"),
                ),
                default=None,
            ),
        ),
    ]
