# Generated by Django 5.2.11 on 2026-03-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0084_add_regression"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regression",
            name="bug_url",
            field=models.URLField(blank=True, help_text="Link to upstream bug tracker"),
        ),
    ]
