# Generated by Django 5.2.11 on 2026-09-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0086_dedupe_and_unique_gamealias_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpamDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=253, unique=True)),
                ("submission_count", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Spam domain",
                "ordering": ("-last_seen",),
            },
        ),
        migrations.AddField(
            model_name="gamesubmission",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
