# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-05 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_auto_20150805_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='tgdb_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
