# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-05 01:00
from __future__ import unicode_literals

from django.db import migrations


PLATFORM_MAP = {
    '3DO': '3do',
    'Arcade': 'arcade',
    'Amiga': 'amiga',
    'Apple II': 'apple-e',
    'Atari 2600': 'atari-2600',
    'Atari 5200': 'atari-5200',
    'Atari ST': 'atari-st',
    'Colecovision': 'colecovision',
    'PC': 'windows',
    'Sega Genesis': 'sega-genesis',
    'Sega Mega Drive': 'sega-genesis',
    'Sega 32X': 'sega-32x',
    'Sega Master System': 'sega-master-system',
    'Sega Saturn': 'sega-saturn',
    'Sega Game Gear': 'sega-game-gear',
    'Sega Dreamcast': 'sega-dreamcast',
    'Atari Jaguar': 'atari-jaguar',
    'Sony Playstation': 'sony-playstation',
    'Sony Playstation 2': 'sony-playstation-2',
    'Sony PSP': 'sony-psp',
    'Sony Playstation Portable': 'sony-psp',
    'Nintendo Entertainment System (NES)': 'nes',
    'Super Nintendo (SNES)': 'super-nintendo',
    'Neo Geo': 'neo-geo',
    'Neo Geo CD': 'neo-geo-cd',
    'Nintendo Game Boy': 'game-boy',
    'Nintendo Game Boy Color': 'nintendo-game-boy-color',
    'Nintendo Game Boy Advance': 'nintendo-game-boy-advance',
    'Nintendo 64': 'nintendo-64',
    'Nintendo GameCube': 'gamecube',
    'Nintendo DS': 'nintendo-ds',
    'Nintendo Wii': 'nintendo-wii',
    'Nintendo Wii U': 'nintendo-wii-u',
    'NeoGeo': 'neo-geo',
    'TurboGrafx 16': 'turbografx-16',
    'Vectrex': 'vectrex',
    'Sinclair ZX Spectrum': 'zx-spectrum',
}


def populate_tgdb_names(apps, schema_editor):
    Platform = apps.get_model('platforms', 'Platform')

    for tgdb_name, slug in PLATFORM_MAP.items():
        Platform.objects.filter(slug=slug).update(tgdb_name=tgdb_name)


class Migration(migrations.Migration):
    dependencies = [
        ('platforms', '0005_platform_tgdb_name'),
    ]

    operations = [
        migrations.RunPython(populate_tgdb_names),
    ]
