# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_populate_tgdb_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='icon',
            field=models.ImageField(blank=True, upload_to='platforms/icons'),
        ),
    ]
