# Generated by Django 2.2.12 on 2021-04-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0007_auto_20180515_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='short_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
