# Generated by Django 2.2.12 on 2021-12-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0009_auto_20211223_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='igdb_id',
            field=models.IntegerField(null=True),
        ),
    ]
